name: sopo
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - python=3.9.20=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.2.post1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - blis==1.0.1
      - catalogue==2.0.10
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - chumpy==0.70
      - click==8.1.7
      - cloudpathlib==0.20.0
      - cmake==3.30.4
      - colorlog==6.8.2
      - confection==0.1.5
      - contourpy==1.3.0
      - cos-python-sdk-v5==1.9.32
      - crcmod==1.7
      - cycler==0.12.1
      - cymem==2.0.8
      - cython==3.0.11
      - diffusers==0.30.3
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - exceptiongroup==1.2.2
      - execnet==2.1.1
      - fastapi==0.115.3
      - filelock==3.16.1
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - ftfy==6.3.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - graphviz==0.8.4
      - grpcio==1.67.0
      - h11==0.14.0
      - h5py==3.12.1
      - huggingface-hub==0.26.0
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.36.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - jinja2==3.1.4
      - joblib==1.2.0
      - kiwisolver==1.4.7
      - langcodes==3.4.1
      - language-data==1.2.0
      - lazy-loader==0.4
      - lightning-utilities==0.11.8
      - lit==18.1.8
      - marisa-trie==1.2.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - murmurhash==1.0.10
      - mxnet-mkl==1.6.0
      - natsort==8.4.0
      - networkx==3.2.1
      - numpy==1.23.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - orjson==3.10.9
      - packaging==24.1
      - pandas==2.2.3
      - peewee==3.17.7
      - pillow==11.0.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - preshed==3.0.9
      - propcache==0.2.0
      - protobuf==5.28.2
      - psutil==6.1.0
      - pycryptodome==3.21.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydeprecate==0.3.2
      - pygments==2.18.0
      - pynvml==11.5.3
      - pyparsing==3.2.0
      - pytest==8.3.3
      - pytest-shutil==1.8.0
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.8.6
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - rich==13.9.2
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scipy==1.13.1
      - sentry-sdk==2.17.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.16.0
      - smart-open==7.0.5
      - smmap==5.0.1
      - smplx==0.1.28
      - sniffio==1.3.1
      - spacy==3.8.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - starlette==0.41.0
      - swanboard==0.1.4b2
      - swankit==0.1.1b3
      - swanlab==0.3.23
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.5.0
      - thinc==8.3.2
      - tifffile==2024.8.30
      - tokenizers==0.20.1
      - tomli==2.0.2
      - torch==2.0.0
      - torchmetrics==0.7.0
      - tqdm==4.66.5
      - transformers==4.45.2
      - trimesh==3.9.24
      - triton==2.0.0
      - typer==0.12.5
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - ujson==5.10.0
      - urllib3==2.2.3
      - uvicorn==0.32.0
      - wandb==0.18.5
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - weasel==0.4.1
      - werkzeug==3.0.4
      - wrapt==1.16.0
      - xmltodict==0.14.2
      - yacs==0.1.8
      - yarl==1.15.5
      - zipp==3.20.2
