version: 1

formatters:
  verysimple:
    format: '%(message)s'

handlers:
  console:
    class: src_tmr.logging.TqdmLoggingHandler
    formatter: verysimple

root:
  level: ${logger_level}
  handlers: [console]


disable_existing_loggers: false
