_target_: src_tmr.model.TEMOS

motion_encoder:
  _target_: src_tmr.model.ACTORStyleEncoder
  nfeats: ${data.motion_loader.nfeats}
  vae: true
  latent_dim: 256
  ff_size: 1024
  num_layers: 6
  num_heads: 4
  dropout: 0.1
  activation: gelu

text_encoder:
  _target_: src_tmr.model.ACTORStyleEncoder
  nfeats: 768
  vae: true
  latent_dim: 256
  ff_size: 1024
  num_layers: 6
  num_heads: 4
  dropout: 0.1
  activation: gelu

motion_decoder:
  _target_: src_tmr.model.ACTORStyleDecoder
  nfeats: ${data.motion_loader.nfeats}
  latent_dim: 256
  ff_size: 1024
  num_layers: 6
  num_heads: 4
  dropout: 0.1
  activation: gelu

vae: true

lmd:
  recons: 1.0
  latent: 1.0e-5
  kl: 1.0e-5

lr: 1e-4
