defaults:
  - defaults
  - _self_

run_dir: ./outputs/tmr_humanml3d_guoh3dfeats
npy: ./datasets/motions/humanml3d/new_joint_vecs/001034.npy
feats: false
text: A guy is getting ready to do a backflip, but he fails and lands on the floor.

ckpt_name: last
device: cuda
